[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = ['npm install -g pnpm && pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm prisma generate && pnpm tsc -p tsconfig.json']

[start]
cmd = 'pnpm prisma migrate deploy && node dist/main.js'

[variables]
NODE_ENV = 'production'